print(bool(""))
print(bool([]))
print(bool(()))
print(bool({}))
print(bool(0))
print(bool(0.0))
print(bool(None))
print()

print(bool("some string/data"))
print(bool(['item1']))
print(bool(('item1')))
print(bool({"item1", "item2"}))
print(bool({"key1: value1"}))
print(bool(1))
print(bool(0.01))
print()
